# Generated by Django 4.2.7 on 2023-11-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasharaapp', '0003_products_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='origin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
