# Generated by Django 4.2.7 on 2023-11-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biasharaapp', '0004_alter_products_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='White', max_length=30),
        ),
    ]
